# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x02\x66l\"h\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x11\n\tframework\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"|\n\tTrainPlan\x12\x10\n\x08round_id\x18\x01 \x01(\t\x12\x11\n\toptimizer\x18\x02 \x01(\t\x12\n\n\x02lr\x18\x03 \x01(\x02\x12\x14\n\x0clocal_epochs\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x14\n\x0csend_metrics\x18\x06 \x01(\x08\",\n\tModelBlob\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"E\n\x11PullGlobalRequest\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.fl.ClientInfo\x12\x10\n\x08round_id\x18\x02 \x01(\t\"V\n\x12PullGlobalResponse\x12#\n\x0cglobal_model\x18\x01 \x01(\x0b\x32\r.fl.ModelBlob\x12\x1b\n\x04plan\x18\x02 \x01(\x0b\x32\r.fl.TrainPlan\"\x88\x01\n\x0bLocalUpdate\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.fl.ClientInfo\x12\x10\n\x08round_id\x18\x02 \x01(\t\x12\x1d\n\x06update\x18\x03 \x01(\x0b\x32\r.fl.ModelBlob\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x03\x12\x13\n\x0bmetric_json\x18\x05 \x01(\t\"8\n\x03\x41\x63k\x12\x10\n\x08round_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"U\n\x05\x43hunk\x12\x10\n\x08round_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0c\n\x04last\x18\x05 \x01(\x08\x32\xf8\x01\n\tFederated\x12;\n\nPullGlobal\x12\x15.fl.PullGlobalRequest\x1a\x16.fl.PullGlobalResponse\x12&\n\nPushUpdate\x12\x0f.fl.LocalUpdate\x1a\x07.fl.Ack\x12\x36\n\x10PullGlobalStream\x12\x15.fl.PullGlobalRequest\x1a\t.fl.Chunk0\x01\x12(\n\x10PushUpdateStream\x12\t.fl.Chunk\x1a\x07.fl.Ack(\x01\x12$\n\tHeartbeat\x12\x0e.fl.ClientInfo\x1a\x07.fl.AckB\x06P\x01Z\x02\x66lb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z\002fl'
  _globals['_CLIENTINFO']._serialized_start=16
  _globals['_CLIENTINFO']._serialized_end=120
  _globals['_TRAINPLAN']._serialized_start=122
  _globals['_TRAINPLAN']._serialized_end=246
  _globals['_MODELBLOB']._serialized_start=248
  _globals['_MODELBLOB']._serialized_end=292
  _globals['_PULLGLOBALREQUEST']._serialized_start=294
  _globals['_PULLGLOBALREQUEST']._serialized_end=363
  _globals['_PULLGLOBALRESPONSE']._serialized_start=365
  _globals['_PULLGLOBALRESPONSE']._serialized_end=451
  _globals['_LOCALUPDATE']._serialized_start=454
  _globals['_LOCALUPDATE']._serialized_end=590
  _globals['_ACK']._serialized_start=592
  _globals['_ACK']._serialized_end=648
  _globals['_CHUNK']._serialized_start=650
  _globals['_CHUNK']._serialized_end=735
  _globals['_FEDERATED']._serialized_start=738
  _globals['_FEDERATED']._serialized_end=986
# @@protoc_insertion_point(module_scope)
