# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fl_pb2 as fl__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullGlobal = channel.unary_unary(
                '/fl.Federated/PullGlobal',
                request_serializer=fl__pb2.PullGlobalRequest.SerializeToString,
                response_deserializer=fl__pb2.PullGlobalResponse.FromString,
                _registered_method=True)
        self.PushUpdate = channel.unary_unary(
                '/fl.Federated/PushUpdate',
                request_serializer=fl__pb2.LocalUpdate.SerializeToString,
                response_deserializer=fl__pb2.Ack.FromString,
                _registered_method=True)
        self.PullGlobalStream = channel.unary_stream(
                '/fl.Federated/PullGlobalStream',
                request_serializer=fl__pb2.PullGlobalRequest.SerializeToString,
                response_deserializer=fl__pb2.Chunk.FromString,
                _registered_method=True)
        self.PushUpdateStream = channel.stream_unary(
                '/fl.Federated/PushUpdateStream',
                request_serializer=fl__pb2.Chunk.SerializeToString,
                response_deserializer=fl__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/fl.Federated/Heartbeat',
                request_serializer=fl__pb2.ClientInfo.SerializeToString,
                response_deserializer=fl__pb2.Ack.FromString,
                _registered_method=True)


class FederatedServicer(object):
    """Service
    """

    def PullGlobal(self, request, context):
        """Small/medium models (simple path)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullGlobalStream(self, request, context):
        """Large models (chunked streaming path)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushUpdateStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Health/heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullGlobal': grpc.unary_unary_rpc_method_handler(
                    servicer.PullGlobal,
                    request_deserializer=fl__pb2.PullGlobalRequest.FromString,
                    response_serializer=fl__pb2.PullGlobalResponse.SerializeToString,
            ),
            'PushUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PushUpdate,
                    request_deserializer=fl__pb2.LocalUpdate.FromString,
                    response_serializer=fl__pb2.Ack.SerializeToString,
            ),
            'PullGlobalStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PullGlobalStream,
                    request_deserializer=fl__pb2.PullGlobalRequest.FromString,
                    response_serializer=fl__pb2.Chunk.SerializeToString,
            ),
            'PushUpdateStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PushUpdateStream,
                    request_deserializer=fl__pb2.Chunk.FromString,
                    response_serializer=fl__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=fl__pb2.ClientInfo.FromString,
                    response_serializer=fl__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl.Federated', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fl.Federated', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Federated(object):
    """Service
    """

    @staticmethod
    def PullGlobal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.Federated/PullGlobal',
            fl__pb2.PullGlobalRequest.SerializeToString,
            fl__pb2.PullGlobalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.Federated/PushUpdate',
            fl__pb2.LocalUpdate.SerializeToString,
            fl__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullGlobalStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fl.Federated/PullGlobalStream',
            fl__pb2.PullGlobalRequest.SerializeToString,
            fl__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushUpdateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fl.Federated/PushUpdateStream',
            fl__pb2.Chunk.SerializeToString,
            fl__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.Federated/Heartbeat',
            fl__pb2.ClientInfo.SerializeToString,
            fl__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
